### ISSUE TITLE
Not compatible with DragRuler

### ISSUE THREAD

**Issue by ravingdragoon** [caewok/fvtt-lib-ruler#2]
Receive a Libwrapper message that the two modules may conflict, and receive incorrect measurements. Receive the same message about Elevation Ruler.

**Comment by manuelVo** [comment]
That's the fault of Drag Ruler. Please open an issue in the Drag Ruler Repository about this.

**Comment by ravingdragoon** [comment]
Ok. I have opened an issue with your(?) Drag Ruler Repository.
