### ISSUE TITLE
priorDest is being set in the wrong spot

### ISSUE THREAD

**Issue by ironmonk108** [caewok/fvtt-lib-ruler#3]
Currently there is a wrapper conflict between Monk's Active Tiles and lib Ruler.
I'm overriding the moveToken code because I think there's a bug in Foundry code, and I tried to fix it, and without it I can't stop tokens from moving.

I believe
`export async function libRulerAnimateToken(token, ray, dx, dy, segment_num) {
  log(`Animating token for segment_num ${segment_num}`);
  
  // Adjust the ray based on token size
  const dest = canvas.grid.getTopLeft(ray.B.x, ray.B.y);
  const path = new Ray({x: token.data.x, y: token.data.y}, {x: dest[0] + dx, y: dest[1] + dy});
  
  // Commit the movement and update the final resolved destination coordinates
  await token.document.update(path.B);
  path.B.x = token.data.x;
  path.B.y = token.data.y;
 
  // Update the path which may have changed during the update, and animate it
  const priorDest = path.B;
  await token.animateMovement(path);
  
  return priorDest;
}`

should be changed to 

`export async function libRulerAnimateToken(token, ray, dx, dy, segment_num) {
  log(`Animating token for segment_num ${segment_num}`);
  
  // Adjust the ray based on token size
  const dest = canvas.grid.getTopLeft(ray.B.x, ray.B.y);
  const path = new Ray({x: token.data.x, y: token.data.y}, {x: dest[0] + dx, y: dest[1] + dy});
  
  // Commit the movement and update the final resolved destination coordinates
  const priorDest = duplicate(path.B);
  await token.document.update(path.B);
  path.B.x = token.data.x;
  path.B.y = token.data.y;
  
  // Update the path which may have changed during the update, and animate it
  await token.animateMovement(path);
  
  return priorDest;
}`

otherwise priorDest will always equal the Token's current destination, and the check in libRulerMoveToken for priorDest being moved will never fail.
With priorDest being set before the update, it gives my module a chance to change it in the preUpdateToken Hook and have the ruler cancel the remaining rays because they're no longer valid.

Thank you.  :-)

**Comment by caewok** [comment]
Thanks! Release 0.1.3 should resolve this. Please re-open if not fixed.
